data:
  - id: 'YRY:Vehicle:ea300803-636f-339c-aa00-2c9f5f13f967'
    lat: 59.904602
    lon: 10.787233
    system: Ryde_Oslo
    isAvailable: true
    name: Ryde
    operator: 'YRY:Operator:Ryde'
    currentRangeMeters: 16400
    distance: 37.1939471672054
    walkingTime: 0.446327366006464
    walkingTimeHumanReadable: Less than a minute-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/Ryde%20Technology%20Logo.svg
  - id: 'YRY:Vehicle:ea321976-7ad2-3028-9bd8-d06d9f3a842e'
    lat: 59.90489
    lon: 10.787884
    system: Ryde_Oslo
    isAvailable: true
    name: Ryde
    operator: 'YRY:Operator:Ryde'
    currentRangeMeters: 3599
    distance: 53.4545839291027
    walkingTime: 0.641455007149232
    walkingTimeHumanReadable: Less than a minute-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/Ryde%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:03d54dc9-2a4b-4fb8-8e93-7186010dbc4c'
    lat: 59.90449
    lon: 10.786726
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 59200
    distance: 59.5157850102747
    walkingTime: 0.714189420123296
    walkingTimeHumanReadable: Less than a minute-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:6d835b76-2065-4983-ba29-82bc007f0c2f'
    lat: 59.90462
    lon: 10.786679
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 68000
    distance: 65.7061157294976
    walkingTime: 0.788473388753971
    walkingTimeHumanReadable: Less than a minute-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:41f82c1b-3f76-4728-9632-24864f54e596'
    lat: 59.90416
    lon: 10.788911
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 32000
    distance: 68.9058792727357
    walkingTime: 0.826870551272828
    walkingTimeHumanReadable: Less than a minute-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:b2454afc-3f8c-4dce-b91c-4fee630dd33e'
    lat: 59.903748
    lon: 10.787522
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 48000
    distance: 75.2432416986822
    walkingTime: 0.902918900384187
    walkingTimeHumanReadable: Less than a minute-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:6930c221-92f8-42bf-a38f-bfb37942d326'
    lat: 59.904922
    lon: 10.789181
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 44000
    distance: 96.4402514340528
    walkingTime: 1.15728301720863
    walkingTimeHumanReadable: 1 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:b891b19f-f5d3-45ea-89b7-aea2fda9ffbf'
    lat: 59.90495
    lon: 10.789203
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 32800
    distance: 99.2794643075919
    walkingTime: 1.1913535716911
    walkingTimeHumanReadable: 1 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:97614e14-9003-40b6-9f0a-166d0cb0cf77'
    lat: 59.90394
    lon: 10.789386
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 43200
    distance: 103.698912764004
    walkingTime: 1.24438695316804
    walkingTimeHumanReadable: 1 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:b93bae8a-87c5-44c2-9ced-b55b7cd8864f'
    lat: 59.903927
    lon: 10.789456
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 38400
    distance: 107.799277552695
    walkingTime: 1.29359133063234
    walkingTimeHumanReadable: 1 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YRY:Vehicle:ea172079-f98a-39bf-8d6f-45ecc4f48d23'
    lat: 59.90394
    lon: 10.789541
    system: Ryde_Oslo
    isAvailable: true
    name: Ryde
    operator: 'YRY:Operator:Ryde'
    currentRangeMeters: 34400
    distance: 111.238838383564
    walkingTime: 1.33486606060277
    walkingTimeHumanReadable: 1 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/Ryde%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:6735ec0e-b0fc-487f-be71-57d3b8478718'
    lat: 59.903866
    lon: 10.789557
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 32000
    distance: 116.10910735385
    walkingTime: 1.3933092882462
    walkingTimeHumanReadable: 1 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:64034439-790d-445f-a37b-4c9ab59d1096'
    lat: 59.90408
    lon: 10.79024
    system: VOI
    isAvailable: false
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 36800
    distance: 141.938823132388
    walkingTime: 1.70326587758866
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YRY:Vehicle:ea314117-9a0f-3298-8543-76f90d43f475'
    lat: 59.90309
    lon: 10.788
    system: Ryde_Oslo
    isAvailable: true
    name: Ryde
    operator: 'YRY:Operator:Ryde'
    currentRangeMeters: 14000
    distance: 147.501409515211
    walkingTime: 1.77001691418253
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/Ryde%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:325eff74-c62e-4c31-93dd-09f15d3c44c8'
    lat: 59.9029
    lon: 10.788355
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 57600
    distance: 171.135633281404
    walkingTime: 2.05362759937685
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:8649ab13-c54a-4e23-9b7f-5c1b14eb0976'
    lat: 59.90315
    lon: 10.785873
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 25600
    distance: 176.131480470598
    walkingTime: 2.11357776564718
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YRY:Vehicle:ea314559-c932-3213-9e82-432fdab4cdb9'
    lat: 59.902718
    lon: 10.787772
    system: Ryde_Oslo
    isAvailable: true
    name: Ryde
    operator: 'YRY:Operator:Ryde'
    currentRangeMeters: 22400
    distance: 188.365031028983
    walkingTime: 2.2603803723478
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/Ryde%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:9a392d13-103f-4cf0-b0c5-5ad539f5f795'
    lat: 59.905685
    lon: 10.790093
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 25600
    distance: 191.416229478035
    walkingTime: 2.29699475373642
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:32f2164a-37f1-49cd-a057-7816456915cc'
    lat: 59.902885
    lon: 10.78952
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 37600
    distance: 195.503746761886
    walkingTime: 2.34604496114263
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
  - id: 'YVO:Vehicle:3af18219-381a-4bb7-a9fe-8fbf294a7fd9'
    lat: 59.90273
    lon: 10.789034
    system: VOI
    isAvailable: true
    name: VOI
    operator: 'YVO:Operator:voi'
    currentRangeMeters: 72000
    distance: 199.633974667044
    walkingTime: 2.39560769600453
    walkingTimeHumanReadable: 2 minutes-ish
    iconUrl: >-
      https://pub-8880548ea82e4e66913439824e2f4be4.r2.dev/VOI%20Technology%20Logo.svg
